"use client";

import React, { useRef } from "react";
import { selectUser, setCredentials } from "@/features/auth/slice";
import { useAppSelector, useAppStore } from "@/store/hooks";
// import { cookies } from "next/headers";
import { jwtDecode } from "jwt-decode";
import { DecodedToken } from "@/features/auth/types";
// export const metadata: Metadata = {
//   title: "Create New JT Doc",
//   description: "Generated by create next app",
// };
const Create = () => {
  // const dispatch = useAppDispatch();
  const { dispatch } = useAppStore();
  const initialized = useRef(false);

  if (!initialized.current) {
    const token = document?.cookie
      .split("; ")
      .find((i) => i.startsWith("token="))
      ?.replace("token=", "");

    if (token) {
      const decoded = jwtDecode<DecodedToken>(token);

      dispatch(
        setCredentials({
          user: {
            id: decoded.sub,
            firstName: decoded.firstName,
            lastName: decoded.lastName,
            email: decoded.email,
          },
          token,
        })
      );
      initialized.current = true;
    }
  }

  // const selectUser = useAppSelector((state: RootState) => state.auth);
  // useSelector
  const user = useAppSelector(selectUser);

  return (
    <main className="p-4">
      <div className="flex justify-between items-center">
        <input
          className="focus:border border-accent outline-none rounded p-2"
          placeholder="Untitled Document"
        />
        <div>
          <span className="border p-2 rounded-full bg-white font-bold">
            {user?.firstName}
          </span>
        </div>
      </div>
      <div></div>
    </main>
  );
};

export default Create;
