import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create New JT Doc",
  description: "Generated by create next app",
};
const Create = () => {
  return (
    <main className="p-4">
      <div className="flex justify-between items-center">
        <input
          className="focus:border border-accent outline-none rounded p-2"
          placeholder="Untitled Document"
        />
        <div>
          <span className="border p-2 rounded-full bg-white font-bold">JO</span>
        </div>
      </div>
      <div></div>
    </main>
  );
};

export default Create;
