import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "Create New JTDoc",
  description: "Generated by create next app",
};

const Docs = () => {
  return (
    <div>Docs</div>
  )
}

export default Docs